name: bazur
description: Extensible parallel dictionary
publish_to: "none"
version: 1.1.2+72

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.18.0
  cloud_firestore: ^3.1.18
  url_launcher: ^6.1.4
  shared_preferences: ^2.0.15
  firebase_auth: ^3.3.20
  google_sign_in: ^5.3.3
  sign_in_with_apple: ^4.0.0
  crypto: ^3.0.2
  algolia: ^1.1.1
  markdown: ^5.0.0
  flutter_markdown: ^0.6.10+2
  package_info_plus: ^1.4.2
  provider: ^6.0.3
  infinite_scroll_pagination: ^3.2.0
  flutter_map: ^1.1.1
  flutter_map_marker_cluster: ^0.5.0
  latlong2: ^0.8.1
  intersperse: ^2.0.0
  google_fonts: ^3.0.1
  auto_route: ^4.2.0
  url_strategy: ^0.2.0
  modal_bottom_sheet: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^2.0.1
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
  auto_route_generator: ^4.2.0

flutter_icons:
  image_path: "assets/icon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
 
               
        